'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm1
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''Lbl_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Name As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Lbl_Designation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Designation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Lbl_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Email As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Btn_UserReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_UserReg As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Btn_StudReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_StudReg As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Btn_PWIS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_PWIS As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Btn_SendEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_SendEmail As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Btn_Logout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Logout As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GView_Students control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GView_Students As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''Txt_Subj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Subj As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Txt_Body control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Body As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Lbl_Template control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Template As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FUpload_Template control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUpload_Template As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''Lbl_Attachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Attachment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FUpload_Attachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUpload_Attachment As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''Btn_Send control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Send As Global.System.Web.UI.WebControls.Button
End Class
